apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appname }}-backend-volume
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.backend.persistentVolumeStorage }}
  accessModes:
  - ReadWriteMany
  hostPath:
    path: {{ .Values.backend.localStoragePath }}/backend