apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-database
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appname }}-database
spec:
  selector:
    app: {{ .Values.appname }}-database
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}