apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appname }}-database-volume
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.database.persistentVolumeStorage }}
  accessModes:
  - ReadWriteMany
  hostPath:
    path: {{ .Values.database.localStoragePath }}/database